/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Player : PlayerBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Player.def
	// Please inherit and implement "class Player : PlayerBase"
	public abstract class PlayerBase : Entity
	{
		public EntityBaseEntityCall_PlayerBase baseEntityCall = null;
		public EntityCellEntityCall_PlayerBase cellEntityCall = null;

		public UInt64 dbid = 0;
		public virtual void onDbidChanged(UInt64 oldValue) {}
		public UInt16 server_id = 0;
		public virtual void onServer_idChanged(UInt16 oldValue) {}


		public PlayerBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_PlayerBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_PlayerBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Player"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Player"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 7:
						UInt64 oldval_dbid = dbid;
						dbid = stream.readUint64();

						if(prop.isBase())
						{
							if(inited)
								onDbidChanged(oldval_dbid);
						}
						else
						{
							if(inWorld)
								onDbidChanged(oldval_dbid);
						}

						break;
					case 40001:
						KBVector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 40000:
						KBVector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 2:
						UInt16 oldval_server_id = server_id;
						server_id = stream.readUint16();

						if(prop.isBase())
						{
							if(inited)
								onServer_idChanged(oldval_server_id);
						}
						else
						{
							if(inWorld)
								onServer_idChanged(oldval_server_id);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Player"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			UInt64 oldval_dbid = dbid;
			Property prop_dbid = pdatas[4];
			if(prop_dbid.isBase())
			{
				if(inited && !inWorld)
					onDbidChanged(oldval_dbid);
			}
			else
			{
				if(inWorld)
				{
					if(prop_dbid.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDbidChanged(oldval_dbid);
					}
				}
			}

			KBVector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			KBVector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			UInt16 oldval_server_id = server_id;
			Property prop_server_id = pdatas[5];
			if(prop_server_id.isBase())
			{
				if(inited && !inWorld)
					onServer_idChanged(oldval_server_id);
			}
			else
			{
				if(inWorld)
				{
					if(prop_server_id.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onServer_idChanged(oldval_server_id);
					}
				}
			}

		}
	}
}